# ~/.bash_aliases
# v.2019-03-28

alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
alias gam="$HOME/bin/gam/gam"
alias ls="ls -1G"
alias mergepdf="/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py"
alias nano="nano -m -u -W --tabsize=4 --fill=85 --autoindent"
alias tb="nc termbin.com 9999"
alias timestamp="date +'%F %r' | tr -d '\n' | pbcopy"
alias weather="curl http://wttr.in/texarkana"
