execute pathogen#infect()
map <F1> :NERDTreeToggle<CR>
syntax on
filetype plugin indent on
" auto word wrap to 80 columns
"set textwidth=80
"set formatoptions+=t
"au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown tw=80 fo+=t colorcolumn=80
"set laststatus=2
