execute pathogen#infect()
filetype plugin indent on

" options
set laststatus=2
set textwidth=80
set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4
set wrapmargin=2
set mouse=a

" ultisnips
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<c-j>'
let g:UltiSnipsJumpBackwardTrigger = '<c-k>'
let g:UltiSnipsListSnippets = '<c-tab>'
let g:UltiSnipsSnippetDirectories=[$HOME."/.vim/mysnippets"]
