#!/bin/bash
# dumpPageLinks
#
# dumps all links on a webpage to a text file

# check for lynx
command -v lynx >/dev/null 2>&1 || { echo "This script requires lynx." >&2; exit 1; }

# variables
lynxopts=( -dump -listonly -nonumbers -notitle )

# prompt the user for the url
printf "%s\n" "Enter the url and press [ENTER] "
read -ep "url: " url

# prompt the user for the output file
printf "%s\n" "Enter the textfile name and press [ENTER] "
read -ep "filename: " f_name

# download all links from the url
lynx "${lynxopts[@]}" "$url" > "$f_name.txt"
