#!/bin/bash
#
# setup git on linux

git config --global user.name "Josh Lawrence"
git config --global user.email "josh@joshlawrence.me"
git config --global color.ui true
git config --global push.default simple
git config --global color.diff auto
git config --global color.status auto
git config --global color.branch auto

# editor
git config --global core.editor vim

# linux?
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=3600'
