#!/usr/bin/env bash
#
# asks you for your ip and opens ports

# run this script as root
[[ $EUID -ne 0 ]] && { echo "This script must be run as root!" >&2; exit 1; }

# ports to open
MY_PORTS=(9090,9100,3000)

printf "%s\n" "Enter your IP address and press [ENTER] "
read -ep "IP Address: " MY_IP

ufw allow proto tcp from "$MY_IP" to any port "${MY_PORTS[@]}"

echo "make note of your rule number: "

ufw status numbered
